const data = [
  {
    num: '1',
    nameRu: 'Большой шар с рисунком',
    name: 'Large ball with pattern',
    amount: '2',
    year: '1960',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '2',
    nameRu: 'Зелёный шар с цветами',
    name: 'Green ball with flowers',
    amount: '5',
    year: '2000',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'green',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '3',
    nameRu: 'Красный матовый шар',
    name: 'Red matte ball',
    amount: '3',
    year: '1990',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '4',
    nameRu: 'Сосулька красная',
    name: 'Icicle red',
    amount: '2',
    year: '1980',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '5',
    nameRu: 'Красный виноград',
    name: 'Red grapes',
    amount: '4',
    year: '1980',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
  {
    num: '6',
    nameRu: 'Красный шар с рисунком',
    name: 'Red ball with pattern',
    amount: '6',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '7',
    nameRu: 'Молочно-белый шар',
    name: 'Milky-white ball',
    amount: '12',
    year: '1960',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
  {
    num: '8',
    nameRu: 'Красный шар',
    name: 'Red ball',
    amount: '10',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '9',
    nameRu: 'Колокольчик старинный',
    name: 'Vintage bell ',
    amount: '2',
    year: '1950',
    shapeRu: 'колокольчик',
    shape: 'bell',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '10',
    nameRu: 'Белый шар ретро',
    name: 'White retro ball',
    amount: '7',
    year: '1960',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '11',
    nameRu: 'Шишка белая',
    name: 'White cone',
    amount: '11',
    year: '1960',
    shapeRu: 'шишка',
    shape: 'cone',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'small',
    favorite: false,
  },
  {
    num: '12',
    nameRu: 'Белый шар с цветами',
    name: 'White ball with flowers',
    amount: '5',
    year: '1980',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '13',
    nameRu: 'Шар расписной Река',
    name: 'Ball with River pattern',
    amount: '3',
    year: '1970',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'large',
    favorite: true,
  },
  {
    num: '14',
    nameRu: 'Шар расписной Деревня',
    name: 'Ball with Village pattern',
    amount: '4',
    year: '1970',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'large',
    favorite: true,
  },
  {
    num: '15',
    nameRu: 'Колокольчик расписной',
    name: 'Bell with pattern',
    amount: '3',
    year: '1970',
    shapeRu: 'колокольчик',
    shape: 'bell',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '16',
    nameRu: 'Шишка расписная Пейзаж',
    name: 'Cone with Landscape pattern',
    amount: '3',
    year: '1970',
    shapeRu: 'шишка',
    shape: 'cone',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
  {
    num: '17',
    nameRu: 'Шишка расписная',
    name: 'Cone with pattern',
    amount: '7',
    year: '1970',
    shapeRu: 'шишка',
    shape: 'cone',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '18',
    nameRu: 'Желтый шар с бантом',
    name: 'Yellow ball with bow',
    amount: '2',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '19',
    nameRu: 'Желтый шар с паетками',
    name: 'Yellow ball with sequins',
    amount: '12',
    year: '1980',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '20',
    nameRu: 'Красный шар с бантом',
    name: 'Red ball with bow',
    amount: '8',
    year: '1950',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
  {
    num: '21',
    nameRu: 'Красный шар с звёздами',
    name: 'Red ball with stars',
    amount: '4',
    year: '1970',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: true,
  },
  {
    num: '22',
    nameRu: 'Шишка золотая',
    name: 'Gold cone',
    amount: '11',
    year: '1990',
    shapeRu: 'шишка',
    shape: 'cone',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'small',
    favorite: false,
  },
  {
    num: '23',
    nameRu: 'Колокольчик старинный',
    name: 'Vintage bell',
    amount: '9',
    year: '1950',
    shapeRu: 'колокольчик',
    shape: 'bell',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '24',
    nameRu: 'Снежинка изящная',
    name: 'Graceful snowflake',
    amount: '1',
    year: '1940',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '25',
    nameRu: 'Розовый шар с блёстками',
    name: 'Pink ball with glitter',
    amount: '12',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '26',
    nameRu: 'Красно-золотой шар',
    name: 'Red and gold ball',
    amount: '8',
    year: '1960',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '27',
    nameRu: 'Красный шар с узором',
    name: 'Red ball with pattern',
    amount: '4',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '28',
    nameRu: 'Бордовый шар с узором',
    name: 'Burgundy ball with a pattern',
    amount: '10',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '29',
    nameRu: 'Старинный шар с цветами',
    name: 'Vintage ball with flowers',
    amount: '5',
    year: '1950',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: true,
  },
  {
    num: '30',
    nameRu: 'Старинный шар с узором',
    name: 'Vintage ball with pattern',
    amount: '8',
    year: '1950',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: true,
  },
  {
    num: '31',
    nameRu: 'Красный шар с блёстками',
    name: 'Red ball with glitter',
    amount: '8',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '32',
    nameRu: 'Синий шар Вселенная',
    name: 'Blue ball with Universe pattern',
    amount: '11',
    year: '1970',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '33',
    nameRu: 'Синий шар со снежинкой',
    name: 'Blue ball with snowflake',
    amount: '6',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '34',
    nameRu: 'Зелёный  шар с узором',
    name: 'Green ball with pattern',
    amount: '8',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'green',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '35',
    nameRu: 'Фигурка Лис в шарфе',
    name: 'Fox in a scarf figurine ',
    amount: '8',
    year: '1950',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
  {
    num: '36',
    nameRu: 'Сиреневый шар с блёстками',
    name: 'Lilac ball with glitter',
    amount: '1',
    year: '2000',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '37',
    nameRu: 'Зелёный шар с блёстками',
    name: 'Green ball with glitter',
    amount: '6',
    year: '2000',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'green',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '38',
    nameRu: 'Голубой  шар Метель',
    name: 'Blue ball with glitter',
    amount: '6',
    year: '2000',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'blue',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '39',
    nameRu: 'Красная снежинка',
    name: 'Red snowflake',
    amount: '6',
    year: '1990',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '40',
    nameRu: 'Снежинка золотая',
    name: 'Gold snowflake',
    amount: '12',
    year: '2020',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '41',
    nameRu: 'Снежинка арктическая',
    name: 'Arctic snowflake',
    amount: '11',
    year: '2020',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '42',
    nameRu: 'Зелёный шар',
    name: 'Green ball',
    amount: '10',
    year: '1980',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'green',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '43',
    nameRu: 'Снежинка двухцветная',
    name: 'Two-color snowflake',
    amount: '6',
    year: '1960',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '44',
    nameRu: 'Фигурка Ангела',
    name: 'Angel figurine',
    amount: '11',
    year: '1940',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
  {
    num: '45',
    nameRu: 'Снежинка новогодняя',
    name: 'Christmas snowflake',
    amount: '1',
    year: '1980',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '46',
    nameRu: 'Фигурка Мухомор',
    name: 'Amanita figurine',
    amount: '10',
    year: '1950',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'small',
    favorite: false,
  },
  {
    num: '47',
    nameRu: 'Фигурка Колодец',
    name: 'Well figurine',
    amount: '6',
    year: '1950',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'small',
    favorite: false,
  },
  {
    num: '48',
    nameRu: 'Желтый шар с бантом',
    name: 'Yellow ball with bow',
    amount: '6',
    year: '1960',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '49',
    nameRu: 'Снежинка с бирюзой',
    name: 'Еurquoise snowflake',
    amount: '4',
    year: '1980',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '50',
    nameRu: 'Колокольчик большой',
    name: 'Large bell',
    amount: '3',
    year: '2020',
    shapeRu: 'колокольчик',
    shape: 'bell',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '51',
    nameRu: 'Шишка с изморозью',
    name: 'Cone with rime',
    amount: '12',
    year: '1970',
    shapeRu: 'шишка',
    shape: 'cone',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'small',
    favorite: false,
  },
  {
    num: '52',
    nameRu: 'Красный шар с надписью',
    name: 'Red ball with inscription',
    amount: '12',
    year: '1990',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'red',
    sizeRu: 'большой',
    size: 'large',
    favorite: true,
  },
  {
    num: '53',
    nameRu: 'Снежинка серебристая',
    name: 'Silver snowflake',
    amount: '6',
    year: '2020',
    shapeRu: 'снежинка',
    shape: 'snowflake',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '54',
    nameRu: 'Зелёный шар с рисунком',
    name: 'Green ball with pattern',
    amount: '6',
    year: '2010',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'green',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '55',
    nameRu: 'Пряничный домик',
    name: 'Gingerbread house',
    amount: '1',
    year: '1940',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'large',
    favorite: false,
  },
  {
    num: '56',
    nameRu: 'Пряничный теремок',
    name: 'Gingerbread teremok',
    amount: '1',
    year: '1940',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'small',
    favorite: false,
  },
  {
    num: '57',
    nameRu: 'Пряничная избушка',
    name: 'Gingerbread hut',
    amount: '1',
    year: '1940',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '58',
    nameRu: 'Фигурка белого медведя',
    name: 'Polar bear figurine',
    amount: '2',
    year: '1980',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '59',
    nameRu: 'Желтый шар с надписью',
    name: 'Yellow ball with inscription',
    amount: '10',
    year: '1990',
    shapeRu: 'шар',
    shape: 'ball',
    colorRu: 'желтый',
    color: 'yellow',
    sizeRu: 'большой',
    size: 'average',
    favorite: false,
  },
  {
    num: '60',
    nameRu: 'Фигурка Голубь',
    name: 'Dove figurine',
    amount: '12',
    year: '1940',
    shapeRu: 'фигурка',
    shape: 'figurine',
    colorRu: 'желтый',
    color: 'white',
    sizeRu: 'большой',
    size: 'average',
    favorite: true,
  },
];

export default data;
